### ISSUE TITLE
As a researcher I want only necessary fields present in data files to minimize their size

### ISSUE THREAD

**Issue by bbiletskyy** [bbiletskyy/intron-prediction#11]
Our data files `exons.txt` and `genes.txt` contain lots of redundant data.
It seems that `exons.txt` needs only `geneId`, `exonId` and `exonSequence` for data extraction. The `genes.txt` file needs only geneId, exonId, geneSequence. It makes sense to update the data files and the tests and data extraction part.

**Comment by r8zr** [comment]
@bbiletskyy as I understand we should reprocess `exonSequence` file and left there only `geneId`, `exonId ` and `exonSequence`? If yes - where could I find a structure of existing file (btw, I thought that it should contain a header with fields, but I don't see them)?
